baseURL = "https://blog.0x32.co.uk/"
languageCode = "en-us"
title = "0x32++"
theme = ["ananke"]

SectionPagesMenu = "main"
enableRobotsTxt = true
disqusShortname = "0x32"

[pagination]
pagerSize = 10

 [params]
   favicon = ""
   site_logo = ""
   description = "Views from the wrong side of 0x32"
   rss = "https://blog.0x32.co.uk/index.xml"
   featured_image = "Electron.jpg"

[params.ananke.social.share]
networks = [
  "bluesky",
  "x-twitter",
  "facebook",
  "pinterest",
  "reddit",
  "email"
]

[params.ananke.social.follow]
networks = [
  "bluesky",
  "instagram",
  "github",
  "mastodon",
  "rss"
]

[params.ananke.social.bluesky]
username = "alastair-hm.bsky.social"

[params.ananke.social.instagram]
username = "alastair_hm"

[params.ananke.social.github]
username = "alastairhm"

[params.ananke.social.mastodon]
username = "@alastair_hm@mastodon.social"
profilelink = "https://mastodon.social/@alastair_hm"

[taxonomies]
  category = "categories"
  tag = "tags"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "mydeployment"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://blog.0x32.co.uk?region=eu-west-1"

# [[deployment.matchers]] configure behavior for files that match the Pattern.
# See https://golang.org/pkg/regexp/syntax/ for pattern syntax.
# Pattern searching is stopped on first match.

# Samples:

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

