baseURL = "https://blog.0x32.co.uk/"
languageCode = "en-us"
title = "0x32++"
theme = ["ananke"]

SectionPagesMenu = "main"
Paginate = 10
enableRobotsTxt = true
disqusShortname = "0x32"

 [params]
   favicon = ""
   site_logo = ""
   description = "Views from the wrong side of 0x32"
   facebook = ""
   instagram = "https://www.instagram.com/alastair_hm/"
   youtube = "https://www.youtube.com/channel/UCZ9xgE64VDn6RB0mTPqsbPA"
   github = "https://github.com/alastairhm/"
   gitlab = "https://gitlab.com/alastairhm"
   linkedin = "https://www.linkedin.com/in/alastair-montgomery-8b169b14/"
   mastodon = "https://mastodon.me.uk/@Alastair"
   slack = ""
   stackoverflow = "https://stackoverflow.com/users/96534/alastair-montgomery"
   rss = "https://blog.0x32.co.uk/index.xml"
   featured_image = "Electron.jpg"

[taxonomies]
  category = "categories"
  tag = "tags"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "mydeployment"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://blog.0x32.co.uk?region=eu-west-1"

# [[deployment.matchers]] configure behavior for files that match the Pattern.
# See https://golang.org/pkg/regexp/syntax/ for pattern syntax.
# Pattern searching is stopped on first match.

# Samples:

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
